[package]
name = "definitions"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = "2.1.1"
parity-scale-codec-derive = "2.1.0"
hex = "0.4.3"
regex = "1.4.5"
lazy_static = "1.4.0"
sp-core = "3.0.0"


[lib]
name = "definitions"
crate-type = ["lib"]
