[package]
name = "signer"
version = "0.1.0"
authors = ["debris <marek.kotewicz@gmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
base58 = "0.1.0"
base64 = "0.10.1"
blake2-rfc = "0.2.18"
blockies = "0.3"
codec = { package = "parity-scale-codec", version = "2.1.1", default-features = false, features = ["derive"] }
db_handling = {path = "../db_handling"}
ethsign = { version = "0.7.3", default-features = false, features = ["pure-rust"] }
ffi-support = "0.4"
frame-metadata = "13.0.0"
hex = "0.4.3"
jni = { version = "0.16.0", optional = true }
lazy_static = "1.3.0"
libc = "0.2"
pixelate = "0.1"
qrcodegen = "1.4"
raptorq = "1.6.3"
regex = "1.2.1"
rlp = { version = "0.3.0", features = ["ethereum"] }
rustc-hex = "2.1.0"
schnorrkel = "0.8.5"
serde = "1.0"
serde_json = "1.0"
sled = "0.34.6"
substrate-bip39 = "0.3.1"
thiserror = "1.0"
tiny-bip39 = { version = "0.6.1", default-features = false }
tiny-hderive = "0.1"
tiny-keccak = "1.4"
transaction_parsing = {path = "../transaction_parsing"}
transaction_signing = {path = "../transaction_signing"}
zeroize = {version = "1.3.0", features = ["zeroize_derive"]}

[lib]
name = "signer"
crate-type = ["staticlib"]

[features]
default = ["jni"]
