[package]
name = "db_handling"
version = "0.1.0"
authors = ["vera"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sled = "0.34.6"
parity-scale-codec = "2.1.1"
parity-scale-codec-derive = "2.1.0"
hex = "0.4.3"
regex = "1.4.5"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
lazy_static = "1.4.0"
sp-core = "3.0.0"
tiny-bip39 = { version = "0.8.0", default-features = false }
blake2-rfc = "0.2.18"
base58 = "0.1.0"
zeroize = {version = "1.3.0", features = ["zeroize_derive"]}
definitions = {path = "../definitions"}
meta_reading = {path = "../meta_reading"}


